# Generated by Django 5.0.1 on 2024-01-14 17:20

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.TextField()),
                ('image', models.ImageField(upload_to=management.models.slugify_upload)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=management.models.slugify_upload)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
