# Generated by Django 4.1.2 on 2024-01-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name': 'Directors', 'verbose_name_plural': 'Rahbariyat'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Hodimlar'},
        ),
    ]
