# Generated by Django 4.1.2 on 2024-01-18 16:32

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_directors_options_alter_employees_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=180)),
                ('position', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to=management.models.slugify_upload)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'EOLeaders',
                'verbose_name_plural': 'Korxona Tashkilot Yetakchilari',
            },
        ),
        migrations.CreateModel(
            name='OTMLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=180)),
                ('position', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to=management.models.slugify_upload)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'OTMLeaders',
                'verbose_name_plural': 'OTM yetakchilari',
            },
        ),
        migrations.CreateModel(
            name='PELeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=180)),
                ('position', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to=management.models.slugify_upload)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'PELeaders',
                'verbose_name_plural': 'Professional talim yetakchilari',
            },
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Viloyat kengashi'},
        ),
        migrations.AlterField(
            model_name='directors',
            name='fullname',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='directors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='directors',
            name='position',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='employees',
            name='fullname',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=350),
        ),
    ]
