# Generated by Django 4.1.2 on 2024-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_eoleaders_otmleaders_peleaders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='admission_days',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='admission_days',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='eoleaders',
            name='admission_days',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='otmleaders',
            name='admission_days',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='peleaders',
            name='admission_days',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eoleaders',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='otmleaders',
            name='position',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='peleaders',
            name='position',
            field=models.CharField(max_length=300),
        ),
    ]
