# Generated by Django 5.0.1 on 2024-01-14 17:20

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=main.models.slugify_upload)),
                ('image2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=main.models.slugify_upload)),
                ('after', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img1', models.ImageField(upload_to=main.models.slugify_upload)),
                ('img2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('img3', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnersOfGreatHearts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to=main.models.slugify_upload)),
                ('image2', models.ImageField(upload_to=main.models.slugify_upload)),
                ('image3', models.ImageField(upload_to=main.models.slugify_upload)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
