# Generated by Django 5.0.1 on 2024-01-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Announcements', 'verbose_name_plural': "E'lonlar"},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='mainnews',
            options={'verbose_name': 'MainNews', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='ownersofgreathearts',
            options={'verbose_name': 'OwnersOfGreatHearts', 'verbose_name_plural': 'Buyuk Qalb Egalari'},
        ),
    ]
