# Generated by Django 4.1.2 on 2024-01-17 10:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_announcements_options_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='video',
            field=models.FileField(null=True, upload_to=main.models.slugify_upload),
        ),
    ]
