# Generated by Django 4.1.2 on 2024-01-17 21:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainnews_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privileges',
                'verbose_name_plural': 'Imtiyozlar',
            },
        ),
        migrations.CreateModel(
            name='YoungReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=main.models.slugify_upload)),
                ('image1', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('image2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('video', models.FileField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'YoungReception',
                'verbose_name_plural': 'Yoshlar qabulxonasi',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles', 'verbose_name_plural': "Maqola va She'rlar"},
        ),
        migrations.AddField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ownersofgreathearts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='ownersofgreathearts',
            name='image2',
            field=models.ImageField(blank=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='ownersofgreathearts',
            name='image3',
            field=models.ImageField(blank=True, upload_to=main.models.slugify_upload),
        ),
    ]
