# Generated by Django 4.1.2 on 2024-01-18 17:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_privileges_youngreception_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ownersofgreathearts',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='youngreception',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
