# Generated by Django 4.1.2 on 2024-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_announcements_video_alter_announcements_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownersofgreathearts',
            options={'verbose_name': 'OwnersOfGreatHearts', 'verbose_name_plural': 'Muvafaqqiyat Hikoyasi'},
        ),
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='articles',
            name='after',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='ownersofgreathearts',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='youngreception',
            name='title',
            field=models.CharField(max_length=170),
        ),
    ]
