# Generated by Django 4.1.2 on 2024-02-23 21:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ownersofgreathearts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ownersofgreathearts',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='privileges',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youngreception',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
