# Generated by Django 4.1.2 on 2024-03-07 22:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_announcements_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=main.models.slugify_upload)),
                ('video', models.FileField(upload_to=main.models.slugify_upload)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'OAV nigohida',
            },
        ),
        migrations.RenameField(
            model_name='mainnews',
            old_name='img1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='mainnews',
            old_name='img2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='mainnews',
            old_name='img3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='ownersofgreathearts',
            old_name='image1',
            new_name='image',
        ),
    ]
